name: Greet Workflow
on:
  workflow_dispatch:
    
jobs:
  greet:
    runs-on: ubuntu-latest
    name: A job to greet anyone
    steps:
      - name: Send Greet
      - run: echo "${{github.events.inputs.what-to-greet}} ${{github.events.inputs.whom-to-greet}}"
        shell: bash